### ISSUE TITLE
[CoderSchool Android] Project 2 - New York Times Article Search - Ready for review

### ISSUE THREAD

**Issue by yasuosm** [yasuosm/coderschool-project2-nytimes-search#1]
My app is complete. Please review. /cc @coderschoolreview

**Comment by hoanle** [comment]
@yasuosm 
:+1: nice work. A few notes after checking out the code:
-  You should avoid duplicating code. For example, two similar codes: searchArticles & loadMore
- Nice to see you added the search box to the ActionBar!
- Properly used spinners (with populated values) or checkboxes to allow users to select filters
- Properly sent and received relevant filters using a callback to pass data between activities 
- Nice job adding the share intent to the article detail view! However, it seems data are not passed correctly to the share app. 
- You codes are fine. Now focus on cleaning & optimising it

Also, here's a more detailed [Project 2 Feedback Guide here](http://learning.coderschool.vn/snippets/intro_to_android/project_2_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission.

Let us know if you have any other thoughts or questions about this assignment. The next assignment (Twitter Client) will be especially important since it introduces the majority of the remaining pieces necessary to build a fully functional API client with complex feeds of data and user creation.

**Comment by yasuosm** [comment]
@hoanle 
Thank you for your review.
